static const char *style_css =

  "/*\n"
  " * Stylesheet for moauth daemon web interface\n"
  " *\n"
  " * Copyright © 2017 by Michael R Sweet\n"
  " *\n"
  " * Licensed under Apache License v2.0.  See the file \"LICENSE\" for more information.\n"
  " */\n"
  "\n"
  "/* Basic appearance */\n"
  "body {\n"
  "  background: white;\n"
  "  color: black;\n"
  "  font-family: sans-serif;\n"
  "  font-size: 20px;\n"
  "  margin: 0px 20px;\n"
  "}\n"
  "\n"
  "a:link, a:link:hover, a:link:visited {\n"
  "  color: #00c;\n"
  "}\n"
  "\n"
  "a:active {\n"
  "  color: #00f;\n"
  "}\n"
  "\n"
  "div.form {\n"
  "  background: left top no-repeat url(/moauth.png);\n"
  "  margin-left: auto;\n"
  "  margin-right: auto;\n"
  "  padding-left: 148px;\n"
  "  width: 50%;\n"
  "}\n"
  "\n"
  "input[type=\"text\"], input[type=\"email\"], input[type=\"password\"] {\n"
  "  font-family: monospace;\n"
  "}\n"
  "\n"
  "p {\n"
  "  text-align: justify;\n"
  "}\n"
  "\n"
  "pre, code {\n"
  "  background: #eee;\n"
  "}\n"
  "\n"
  "pre {\n"
  "  margin: 1em 40px;\n"
  "  padding: 10px;\n"
  "}\n"
  "\n"
  "code {\n"
  "  padding: 1px 5px;\n"
  "}\n"
  "\n"
  "pre code {\n"
  "  padding: 0px;\n"
  "}\n"
  "\n"
  "blockquote {\n"
  "  border-left: solid 2px #777;\n"
  "  margin: 1em 40px;\n"
  "  padding: 10px;\n"
  "}\n"
  "\n"
  "blockquote p {\n"
  "  margin: 0;\n"
  "}\n"
  "\n"
  "/* Logical row */\n"
  ".row {\n"
  "  width: 100%;\n"
  "  *zoom: 1;\n"
  "}\n"
  ".row:after {\n"
  "  clean: both;\n"
  "}\n"
  "\n"
  "/* Logical columns (12 column grid) */\n"
  ".row .col-6 {\n"
  "  float: left;\n"
  "  margin-left: 0.5%;\n"
  "  margin-right: 0;\n"
  "  width: 49.75%;\n"
  "}\n"
  ".row .col-6:first-child {\n"
  "  margin-left: 0;\n"
  "}\n"
  "\n"
  "/* iPhone/iPod touch overrides */\n"
  "@media (max-device-width: 480px), (max-device-width: 568px) {\n"
  "  /* 6-column layout becomes 12-columns */\n"
  "  .row .col-6 {\n"
  "    float: none;\n"
  "    margin: 0;\n"
  "    width: 100%;\n"
  "  }\n"
  "  div.form {\n"
  "    background: center top no-repeat url(/moauth.png);\n"
  "    margin-left: 0;\n"
  "    margin-right: 0;\n"
  "    padding-left: 0px;\n"
  "    padding-top: 148px;\n"
  "    width: 100%;\n"
  "  }\n"
  "}\n";
