static const char *style_css =

  "/*\n"
  " * Stylesheet for moauth daemon web interface\n"
  " *\n"
  " * Copyright © 2017 by Michael R Sweet\n"
  " *\n"
  " * Licensed under Apache License v2.0.  See the file \"LICENSE\" for more information.\n"
  " */\n"
  "\n"
  "body {\n"
  "  background: white;\n"
  "  color: black;\n"
  "  font-family: sans-serif;\n"
  "}\n"
  "\n"
  "input[type=\"text\"], input[type=\"email\"], input[type=\"password\"] {\n"
  "  font-family: monospace;\n"
  "}\n"
  "\n"
  "blockquote, pre {\n"
  "  background: rgba(127,127,127,0.1);\n"
  "  border-left: solid 2px #7f7f7f;\n"
  "  margin: 1em 40px;\n"
  "  padding: 5px;\n"
  "}\n"
  "\n"
  "blockquote p {\n"
  "  margin: 0;\n"
  "}\n"
  "\n"
  "/* Logical row */\n"
  ".row {\n"
  "  width: 100%;\n"
  "  *zoom: 1;\n"
  "}\n"
  ".row:after {\n"
  "  clean: both;\n"
  "}\n"
  "\n"
  "/* Logical columns (12 column grid) */\n"
  ".row .col-6 {\n"
  "  float: left;\n"
  "  margin-left: 0.5%;\n"
  "  margin-right: 0;\n"
  "  width: 49.75%;\n"
  "}\n"
  ".row .col-6:first-child {\n"
  "  margin-left: 0;\n"
  "}\n"
  "\n"
  "/* iPhone/iPod touch overrides */\n"
  "@media only screen and (min-device-width: 320px) and (max-device-width: 480px),\n"
  "       only screen and (min-device-width: 320px) and (max-device-width: 568px) {\n"
  "  /* 6-column layout becomes 12-columns */\n"
  "  .row .col-6 {\n"
  "    float: none;\n"
  "    margin: 0;\n"
  "    width: 100%;\n"
  "  }\n"
  "}\n";
